sudo:required
services:
  - docker

before_install:
  - docker build -t bankim1982/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run bankim1982/react-test npm test -- --coverage


after_success:
  - docker build -t bankim1982/multi-client ./client
  - docker build -t bankim1982/multi-nginx ./nginx
  - docker build -t bankim1982/multi-server ./server
  - docker build -t bankim1982/multi-worker ./worker
  #Login into docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push bankim1982/multi-client
  - docker push bankim1982/multi-nginx
  - docker push bankim1982/multi-server
  - docker push bankim1982/multi-worker
